### ISSUE TITLE
No me deja hacer push

### ISSUE THREAD

**Issue by chars32** [rafaelmv/Platzi-Shoppy#2]
Cuando quiero hacer push origin master, me dice lo siguiente : 

remote: Permission to rafaelmv/Platzi-Shoppy.git denied to chars32.
fatal: unable to access 'https://github.com/rafaelmv/Platzi-Shoppy.git/': The requested URL returned error:

**Comment by rafaelmv** [comment]
Tienes que hacerle fork al repo, lo arreglas desde tu fork y una vez que esté listo le haces un pull request al original :)
